title: Leo Epstein
description: Graduate student in the CAPS group at University of Idaho.
[CV](github.com/morphogenetics/morphogenetics.github.io/cv.pdf)

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
